import { PrecoItem } from "./TabelaDePrecos";


export const PrecoSofa: Record<number, PrecoItem> = {
    [1]: {
        limpeza: 40,
        impermeabilizacao: 60,
        antiAcaro: 30,
        antiOdor: 15,
        antiFogo: 25,
        hidratacao: 60,
    },
    [2]: {
        limpeza: 75,
        impermeabilizacao: 120,
        antiAcaro: 35,
        antiOdor: 20,
        antiFogo: 35,
        hidratacao: 95,
    },
    [3]: {
        limpeza: 90,
        impermeabilizacao: 160,
        antiAcaro: 40,
        antiOdor: 25,
        antiFogo: 40,
        hidratacao: 125,
    },
    [4]: {
        limpeza: 105,
        impermeabilizacao: 200,
        antiAcaro: 45,
        antiOdor: 27.5,
        antiFogo: 45,
        hidratacao: 145,
    },
    [5]: {
        limpeza: 125,
        impermeabilizacao: 240,
        antiAcaro: 55,
        antiOdor: 30,
        antiFogo: 50,
        hidratacao: 165,
    },
    [6]: {
        limpeza: 145,
        impermeabilizacao: 280,
        antiAcaro: 30,
        antiOdor: 32.5,
        antiFogo: 55,
        hidratacao: 185,
    },
    [7]: {
        limpeza: 165,
        impermeabilizacao: 320,
        antiAcaro: 35,
        antiOdor: 35,
        antiFogo: 60,
        hidratacao: 205,
    },
    [8]: {
        limpeza: 185,
        impermeabilizacao: 360,
        antiAcaro: 40,
        antiOdor: 37.5,
        antiFogo: 65,
        hidratacao: 225,
    },
    [9]: {
        limpeza: 205,
        impermeabilizacao: 400,
        antiAcaro: 45,
        antiOdor: 40,
        antiFogo: 70,
        hidratacao: 250,
    },
    [10]: {
        limpeza: 225,
        impermeabilizacao: 440,
        antiAcaro: 55,
        antiOdor: 42.5,
        antiFogo: 75,
        hidratacao: 275,
    },
};
